#!/bin/zsh

## Android
export ANDROID_HOME="/Users/$USER/Library/Android/sdk"
export PATH="${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
## Homebrew
export HOMEBREW="/opt/homebrew/bin"
export PATH="$PATH:$HOMEBREW"
## GPG
export GPG_TTY=$(tty)
## Java
export JAVA_HOME=$(/usr/libexec/java_home)
