#!/bin/zsh

## Directory Shortcuts
alias development="~/Documents/Development"
alias dice="~/Documents/Development/android-dice"
alias dice_onsite="~/Documents/Development/android-onsite"
alias dotfiles="~/Dotfiles/"

## Sublime
alias edit="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"

## Networking
alias my_ip="curl http://ipecho.net/plain; echo"

## ADB
alias deeplink="adb shell am start -d"

## Chrome
alias github="open -a \"/Applications/Google Chrome.app\" http://www.github.com"
