#!/bin/zsh

## Directory Shortcuts
alias development="~/Documents/Development"
alias dice="~/Documents/Development/Android/DICE-Fan"
alias dice_onsite="~/Documents/Development/Android/DICE-Onsite"
alias dotfiles="~/Dotfiles/"

## Networking
alias my_ip="curl http://ipecho.net/plain; echo"

## ADB
alias deeplink="adb shell am start -d"

## Chrome
alias github_open="open -a \"/Applications/Google Chrome.app\" https://www.github.com"
alias bitrise_open="open -a \"/Applications/Google Chrome.app\" https://app.bitrise.io/dashboard"
