#!/bin/sh

## Git
git_commit_all () {
	git add -A;
	git commit -av -m;
}
git_amend () {
	git status -s;
	git add -A;
	git commit --amend --reuse-message=HEAD
}
git_clean_qa_tags () {
	git tag | grep qa- | xargs -n 1 -I% git push origin :refs/tags/%;
	git tag -d \$(git tag -l 'qa-*')
}
git_delete_tag () {
	git tag --delete \$1;
	git push origin --delete \$1;
}
git_add_tag () {
	git tag \$1;
	git push origin \$1;
}
git_rebase_develop () {
	BRANCH=`git_echo_branch_name`;
	git fetch --prune;
	git checkout develop;
	git pull;
	git checkout \$BRANCH;
	git rebase develop;
}